/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bs_model {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bs_rng {
    _unused: [u8; 0],
}
#[doc = " Type signature for optional print callback"]
pub type STREAM_CALLBACK =
    ::std::option::Option<unsafe extern "C" fn(data: *const ::std::os::raw::c_char, size: usize)>;
pub struct BridgeStan {
    __library: ::libloading::Library,
    pub bs_major_version: *mut ::std::os::raw::c_int,
    pub bs_minor_version: *mut ::std::os::raw::c_int,
    pub bs_patch_version: *mut ::std::os::raw::c_int,
    pub bs_model_construct: unsafe extern "C" fn(
        data: *const ::std::os::raw::c_char,
        seed: ::std::os::raw::c_uint,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> *mut bs_model,
    pub bs_model_destruct: unsafe extern "C" fn(m: *mut bs_model),
    pub bs_free_error_msg: unsafe extern "C" fn(error_msg: *mut ::std::os::raw::c_char),
    pub bs_name: unsafe extern "C" fn(m: *const bs_model) -> *const ::std::os::raw::c_char,
    pub bs_model_info: unsafe extern "C" fn(m: *const bs_model) -> *const ::std::os::raw::c_char,
    pub bs_param_names: unsafe extern "C" fn(
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
    ) -> *const ::std::os::raw::c_char,
    pub bs_param_unc_names:
        unsafe extern "C" fn(m: *const bs_model) -> *const ::std::os::raw::c_char,
    pub bs_param_num: unsafe extern "C" fn(
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
    ) -> ::std::os::raw::c_int,
    pub bs_param_unc_num: unsafe extern "C" fn(m: *const bs_model) -> ::std::os::raw::c_int,
    pub bs_param_constrain: unsafe extern "C" fn(
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
        theta_unc: *const f64,
        theta: *mut f64,
        rng: *mut bs_rng,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_param_unconstrain: unsafe extern "C" fn(
        m: *const bs_model,
        theta: *const f64,
        theta_unc: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_param_unconstrain_json: unsafe extern "C" fn(
        m: *const bs_model,
        json: *const ::std::os::raw::c_char,
        theta_unc: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_log_density: unsafe extern "C" fn(
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        lp: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_log_density_gradient: unsafe extern "C" fn(
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        val: *mut f64,
        grad: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_log_density_hessian: unsafe extern "C" fn(
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        val: *mut f64,
        grad: *mut f64,
        hessian: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_log_density_hessian_vector_product: unsafe extern "C" fn(
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        vector: *const f64,
        val: *mut f64,
        hvp: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub bs_rng_construct: unsafe extern "C" fn(
        seed: ::std::os::raw::c_uint,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> *mut bs_rng,
    pub bs_rng_destruct: unsafe extern "C" fn(rng: *mut bs_rng),
    pub bs_set_print_callback: unsafe extern "C" fn(
        callback: STREAM_CALLBACK,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
}
impl BridgeStan {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let bs_major_version = __library
            .get::<*mut ::std::os::raw::c_int>(b"bs_major_version\0")
            .map(|sym| *sym)?;
        let bs_minor_version = __library
            .get::<*mut ::std::os::raw::c_int>(b"bs_minor_version\0")
            .map(|sym| *sym)?;
        let bs_patch_version = __library
            .get::<*mut ::std::os::raw::c_int>(b"bs_patch_version\0")
            .map(|sym| *sym)?;
        let bs_model_construct = __library.get(b"bs_model_construct\0").map(|sym| *sym)?;
        let bs_model_destruct = __library.get(b"bs_model_destruct\0").map(|sym| *sym)?;
        let bs_free_error_msg = __library.get(b"bs_free_error_msg\0").map(|sym| *sym)?;
        let bs_name = __library.get(b"bs_name\0").map(|sym| *sym)?;
        let bs_model_info = __library.get(b"bs_model_info\0").map(|sym| *sym)?;
        let bs_param_names = __library.get(b"bs_param_names\0").map(|sym| *sym)?;
        let bs_param_unc_names = __library.get(b"bs_param_unc_names\0").map(|sym| *sym)?;
        let bs_param_num = __library.get(b"bs_param_num\0").map(|sym| *sym)?;
        let bs_param_unc_num = __library.get(b"bs_param_unc_num\0").map(|sym| *sym)?;
        let bs_param_constrain = __library.get(b"bs_param_constrain\0").map(|sym| *sym)?;
        let bs_param_unconstrain = __library.get(b"bs_param_unconstrain\0").map(|sym| *sym)?;
        let bs_param_unconstrain_json = __library
            .get(b"bs_param_unconstrain_json\0")
            .map(|sym| *sym)?;
        let bs_log_density = __library.get(b"bs_log_density\0").map(|sym| *sym)?;
        let bs_log_density_gradient = __library
            .get(b"bs_log_density_gradient\0")
            .map(|sym| *sym)?;
        let bs_log_density_hessian = __library.get(b"bs_log_density_hessian\0").map(|sym| *sym)?;
        let bs_log_density_hessian_vector_product = __library
            .get(b"bs_log_density_hessian_vector_product\0")
            .map(|sym| *sym)?;
        let bs_rng_construct = __library.get(b"bs_rng_construct\0").map(|sym| *sym)?;
        let bs_rng_destruct = __library.get(b"bs_rng_destruct\0").map(|sym| *sym)?;
        let bs_set_print_callback = __library.get(b"bs_set_print_callback\0").map(|sym| *sym)?;
        Ok(BridgeStan {
            __library,
            bs_major_version,
            bs_minor_version,
            bs_patch_version,
            bs_model_construct,
            bs_model_destruct,
            bs_free_error_msg,
            bs_name,
            bs_model_info,
            bs_param_names,
            bs_param_unc_names,
            bs_param_num,
            bs_param_unc_num,
            bs_param_constrain,
            bs_param_unconstrain,
            bs_param_unconstrain_json,
            bs_log_density,
            bs_log_density_gradient,
            bs_log_density_hessian,
            bs_log_density_hessian_vector_product,
            bs_rng_construct,
            bs_rng_destruct,
            bs_set_print_callback,
        })
    }
    pub unsafe fn bs_major_version(&self) -> *mut ::std::os::raw::c_int {
        self.bs_major_version
    }
    pub unsafe fn bs_minor_version(&self) -> *mut ::std::os::raw::c_int {
        self.bs_minor_version
    }
    pub unsafe fn bs_patch_version(&self) -> *mut ::std::os::raw::c_int {
        self.bs_patch_version
    }
    #[doc = " Construct an instance of a model wrapper.\n Data must be encoded in JSON in the\n <a href=\"https://mc-stan.org/docs/cmdstan-guide/json.html\">JSON Format for\n CmdStan</a>.\n\n @param[in] data C-style string. This is either a\n path to JSON-encoded data file (must end with \".json\"),\n a JSON string literal, or nullptr. An empty string or null\n pointer are both interpreted as no data.\n @param[in] seed seed for PRNG used during model construction.\n This PRNG is used for RNG functions in the `transformed data`\n block of the model, and then discarded.\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return pointer to constructed model or `nullptr` if construction\n fails"]
    pub unsafe fn bs_model_construct(
        &self,
        data: *const ::std::os::raw::c_char,
        seed: ::std::os::raw::c_uint,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> *mut bs_model {
        (self.bs_model_construct)(data, seed, error_msg)
    }
    #[doc = " Destroy the model.\n\n @param[in] m pointer to model structure"]
    pub unsafe fn bs_model_destruct(&self, m: *mut bs_model) {
        (self.bs_model_destruct)(m)
    }
    #[doc = " Free the error messages created by other methods.\n\n @param[in] error_msg pointer to error message"]
    pub unsafe fn bs_free_error_msg(&self, error_msg: *mut ::std::os::raw::c_char) {
        (self.bs_free_error_msg)(error_msg)
    }
    #[doc = " Return the name of the specified model as a C-style string.\n\n The returned string should not be modified; it is freed when the\n model wrapper is destroyed.\n\n @param[in] m pointer to model and RNG structure\n @return name of model"]
    pub unsafe fn bs_name(&self, m: *const bs_model) -> *const ::std::os::raw::c_char {
        (self.bs_name)(m)
    }
    #[doc = " Return information about the compiled model as a C-style string.\n\n The returned string should not be modified; it is freed when the\n model wrapper is destroyed.\n\n @param[in] m pointer to model structure\n @return Information about the model including Stan version, Stan defines, and\n compiler flags."]
    pub unsafe fn bs_model_info(&self, m: *const bs_model) -> *const ::std::os::raw::c_char {
        (self.bs_model_info)(m)
    }
    #[doc = " Return a comma-separated sequence of indexed parameter names,\n including the transformed parameters and/or generated quantities\n as specified.\n\n The parameters are returned in the order they are declared.\n Multivariate parameters are return in column-major (more\n generally last-index major) order.  Parameters are separated with\n periods (`.`).  For example, `a[3]` is written `a.3` and `b[2,\n 3]` as `b.2.3`.  The numbering follows Stan and is indexed from 1.\n\n The returned string should not be modified; it is freed when the\n model wrapper is destroyed.\n\n @param[in] m pointer to model structure\n @param[in] include_tp `true` to include transformed parameters\n @param[in] include_gq `true` to include generated quantities\n @return CSV-separated, indexed, parameter names"]
    pub unsafe fn bs_param_names(
        &self,
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
    ) -> *const ::std::os::raw::c_char {
        (self.bs_param_names)(m, include_tp, include_gq)
    }
    #[doc = " Return a comma-separated sequence of unconstrained parameters.\n Only parameters are unconstrained, so there are no unconstrained\n transformed parameters or generated quantities.\n\n The parameters are returned in the order they are declared.\n Multivariate parameters are return in column-major (more\n generally last-index major) order.  Parameters are separated with\n periods (`.`).  For example, `a[3]` is written `a.3` and `b[2,\n 3]` as `b.2.3`.  The numbering follows Stan and is indexed from 1.\n\n The returned string should not be modified; it is freed when the\n model wrapper is destroyed.\n\n @param[in] m pointer to model structure\n @return CSV-separated, indexed, unconstrained parameter names"]
    pub unsafe fn bs_param_unc_names(&self, m: *const bs_model) -> *const ::std::os::raw::c_char {
        (self.bs_param_unc_names)(m)
    }
    #[doc = " Return the number of scalar parameters, optionally including the\n number of transformed parameters and/or generated quantities.\n For example, a 2 x 3 matrix counts as 6 scalar parameters.\n\n @param[in] m pointer to model structure\n @param[in] include_tp `true` to include transformed parameters\n @param[in] include_gq `true` to include generated quantities\n @return number of parameters"]
    pub unsafe fn bs_param_num(
        &self,
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
    ) -> ::std::os::raw::c_int {
        (self.bs_param_num)(m, include_tp, include_gq)
    }
    #[doc = " Return the number of unconstrained parameters.  The number of\n unconstrained parameters might be smaller than the number of\n parameters if the unconstrained space has fewer dimensions than\n the constrained (e.g., for simplexes or correlation matrices).\n\n @param[in] m pointer to model structure\n @return number of unconstrained parameters"]
    pub unsafe fn bs_param_unc_num(&self, m: *const bs_model) -> ::std::os::raw::c_int {
        (self.bs_param_unc_num)(m)
    }
    #[doc = " Set the sequence of constrained parameters based on the specified\n unconstrained parameters, including transformed parameters and/or\n generated quantities as specified, and return a return code of 0\n for success and -1 for failure.  Parameter order is as declared\n in the Stan program, with multivariate parameters given in\n last-index-major order.\n\n @param[in] m pointer to model structure\n @param[in] include_tp `true` to include transformed parameters\n @param[in] include_gq `true` to include generated quantities\n @param[in] theta_unc sequence of unconstrained parameters\n @param[out] theta sequence of constrained parameters\n @param[in] rng pointer to pseudorandom number generator, should be created\n by bs_rng_construct(). This is only required when `include_gq` is `true`,\n otherwise it can be null.\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_param_constrain(
        &self,
        m: *const bs_model,
        include_tp: bool,
        include_gq: bool,
        theta_unc: *const f64,
        theta: *mut f64,
        rng: *mut bs_rng,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_param_constrain)(m, include_tp, include_gq, theta_unc, theta, rng, error_msg)
    }
    #[doc = " Set the sequence of unconstrained parameters based on the\n specified constrained parameters, and return a return code of 0\n for success and -1 for failure.  Parameter order is as declared\n in the Stan program, with multivariate parameters given in\n last-index-major order.\n\n @param[in] m pointer to model structure\n @param[in] theta sequence of constrained parameters\n @param[out] theta_unc sequence of unconstrained parameters\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_param_unconstrain(
        &self,
        m: *const bs_model,
        theta: *const f64,
        theta_unc: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_param_unconstrain)(m, theta, theta_unc, error_msg)
    }
    #[doc = " Set the sequence of unconstrained parameters based on the JSON\n specification of the constrained parameters, and return a return\n code of 0 for success and -1 for failure.\n The JSON is expected to be in the\n <a href=\"https://mc-stan.org/docs/cmdstan-guide/json.html\">JSON Format for\n CmdStan</a>.\n\n @param[in] m pointer to model structure\n @param[in] json JSON-encoded constrained parameters\n @param[out] theta_unc sequence of unconstrained parameters\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_param_unconstrain_json(
        &self,
        m: *const bs_model,
        json: *const ::std::os::raw::c_char,
        theta_unc: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_param_unconstrain_json)(m, json, theta_unc, error_msg)
    }
    #[doc = " Set the log density of the specified parameters, dropping\n constants if `propto` is `true` and including the Jacobian terms\n resulting from constraining parameters if `jacobian` is `true`,\n and return a return code of 0 for success and -1 if there is an\n exception executing the Stan program.\n\n @param[in] m pointer to model structure\n @param[in] propto `true` to discard constant terms\n @param[in] jacobian `true` to include change-of-variables terms\n @param[in] theta_unc unconstrained parameters\n @param[out] lp log density to be set\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_log_density(
        &self,
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        lp: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_log_density)(m, propto, jacobian, theta_unc, lp, error_msg)
    }
    #[doc = " Set the log density and gradient of the specified parameters,\n dropping constants if `propto` is `true` and including the\n Jacobian terms resulting from constraining parameters if\n `jacobian` is `true`, and return a return code of 0 for success\n and -1 if there is an exception executing the Stan program.  The\n gradient must have enough space to hold the gradient.\n\n The gradients are computed using automatic differentiation.\n\n @param[in] m pointer to model structure\n @param[in] propto `true` to discard constant terms\n @param[in] jacobian `true` to include change-of-variables terms\n @param[in] theta_unc unconstrained parameters\n @param[out] val log density to be set\n @param[out] grad gradient to set\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_log_density_gradient(
        &self,
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        val: *mut f64,
        grad: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_log_density_gradient)(m, propto, jacobian, theta_unc, val, grad, error_msg)
    }
    #[doc = " Set the log density, gradient, and Hessian of the specified parameters,\n dropping constants if `propto` is `true` and including the\n Jacobian terms resulting from constraining parameters if\n `jacobian` is `true`, and return a return code of 0 for success\n and -1 if there is an exception executing the Stan program.  The\n pointer `grad` must have enough space to hold the gradient.  The\n pointer `hessian` must have enough space to hold the Hessian.\n\n The gradients are computed using automatic differentiation.\n Hessians are computed using nested automatic differentiation if\n `BRIDGESTAN_AD_HESSIAN` is defined, otherwise they are computed\n using central finite differences of `size(theta_unc)` calculations\n of gradient.\n\n @param[in] m pointer to model structure\n @param[in] propto `true` to discard constant terms\n @param[in] jacobian `true` to include change-of-variables terms\n @param[in] theta_unc unconstrained parameters\n @param[out] val log density to be set\n @param[out] grad gradient to set\n @param[out] hessian hessian to set\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_log_density_hessian(
        &self,
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        val: *mut f64,
        grad: *mut f64,
        hessian: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_log_density_hessian)(
            m, propto, jacobian, theta_unc, val, grad, hessian, error_msg,
        )
    }
    #[doc = " Calculate the log density and the product of the Hessian with the specified\n vector for the specified unconstrained parameters and write it into the\n specified value pointer and Hessian-vector product pointer, dropping\n constants it `propto` is `true` and including the Jacobian adjustment if\n `jacobian` is `true`. Returns a return code of 0 for success\n and -1 if there is an exception executing the Stan program. The\n pointer `hvp` must have enough space to hold the product.\n\n Hessian-vector-products are computed using nested automatic\n differentiation if `BRIDGESTAN_AD_HESSIAN` is defined, otherwise\n they are computed using central finite differences of the gradient\n of `theta_unc` perturbed in the direction of `vector`. This\n approximates the Hessian-vector product using two gradient\n evaluations, but at a lower accuracy than the nested automatic\n differentiation.\n\n @param[in] m pointer to model structure\n @param[in] propto `true` to drop constant terms\n @param[in] jacobian `true` to include Jacobian adjustment for\n constrained parameter transforms\n @param[in] theta_unc unconstrained parameters\n @param[in] vector vector to multiply Hessian by\n @param[out] val log density to set\n @param[out] hvp Hessian-vector to set\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception\n in the underlying Stan code"]
    pub unsafe fn bs_log_density_hessian_vector_product(
        &self,
        m: *const bs_model,
        propto: bool,
        jacobian: bool,
        theta_unc: *const f64,
        vector: *const f64,
        val: *mut f64,
        hvp: *mut f64,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_log_density_hessian_vector_product)(
            m, propto, jacobian, theta_unc, vector, val, hvp, error_msg,
        )
    }
    #[doc = " Construct an PRNG object to be used in bs_param_constrain().\n This object is not thread safe and should be constructed and\n destructed for each thread.\n\n @param[in] seed seed for the RNG\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg()."]
    pub unsafe fn bs_rng_construct(
        &self,
        seed: ::std::os::raw::c_uint,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> *mut bs_rng {
        (self.bs_rng_construct)(seed, error_msg)
    }
    #[doc = " Destruct an RNG object.\n\n @param[in] rng pointer to RNG object"]
    pub unsafe fn bs_rng_destruct(&self, rng: *mut bs_rng) {
        (self.bs_rng_destruct)(rng)
    }
    #[doc = " Provide a function for printing. This will be called when the Stan\n model prints output. The default is to print to stdout.\n\n @param[in] callback function to call when the Stan model prints. This\n function will be guarded by a mutex, so it need not be thread safe. It must\n never propagate an exception. Passing NULL will redirect printing back to\n stdout.\n @param[out] error_msg a pointer to a string that will be allocated if there\n is an error. This must later be freed by calling bs_free_error_msg().\n @return code 0 if successful and code -1 if there is an exception"]
    pub unsafe fn bs_set_print_callback(
        &self,
        callback: STREAM_CALLBACK,
        error_msg: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.bs_set_print_callback)(callback, error_msg)
    }
}
