library(nutpieR)
library(testthat)
args <- commandArgs(trailingOnly = TRUE)
fixtures <- normalizePath(args[[1]], mustWork = TRUE)
root <- tempfile("byok-examples-"); dir.create(root)
make_kernel <- function(mode) {
  work <- file.path(root, paste0("mode", mode)); dir.create(work, showWarnings=FALSE)
  file.copy(file.path(fixtures,"gaussian.c"),work,overwrite=TRUE)
  old <- setwd(work); on.exit(setwd(old))
  Sys.setenv(PKG_CPPFLAGS=paste0('-I"',system.file("include",package="nutpieR"),'" -DFIXTURE_MODE=',mode))
  status <- system2(file.path(R.home("bin"),"R"),c("CMD","SHLIB","gaussian.c"),stdout="build.log",stderr="build.log",timeout=90)
  stopifnot(status==0L)
  normalizePath(paste0("gaussian",.Platform$dynlib.ext))
}
normal_ref <- nutpie_compile_model(file.path(fixtures,"gaussian.stan"))
positive_ref <- nutpie_compile_model(file.path(fixtures,"positive.stan"))
normal <- nutpie_attach_kernel(normal_ref,make_kernel(0),list(n=2L,mu=1,sigma=2))
positive <- nutpie_attach_kernel(positive_ref,make_kernel(15),list(n=2L,mu=1,sigma=2))
# First run intentionally unchecked: advisory validation cannot be a sampling gate.
fit <- nutpie_sample(normal,num_draws=500,num_warmup=300,num_chains=4,cores=2,seed=421,progress="none",save_warmup=TRUE,store_gradient=TRUE,store_unconstrained=TRUE,store_mass_matrix=TRUE,store_divergences=TRUE)
expect_s3_class(fit,"draws_array")
expect_equal(dim(fit)[1:2],c(500L,4L))
expect_true(all(is.finite(fit)))
print(dimnames(fit)[[3]])
for (n in c("x[1]","x[2]")) {
  expect_lt(abs(mean(fit[,,n])-1),0.25)
  expect_lt(abs(sd(as.numeric(fit[,,n]))-2),0.25)
}
expect_equal(dim(nutpie_warmup_draws(fit))[1:2],c(300L,4L))
expect_equal(length(nutpie_diagnostics(fit)$chain),2000L)
expect_equal(length(nutpie_warmup_diagnostics(fit)$chain),1200L)
expect_identical(nutpie_validate_kernel(normal)$status,"pass")
expect_identical(nutpie_validate_kernel(positive)$status,"pass")
for (adapt in c("diag","low_rank")) {
  cat("POSITIVE",adapt,"\n")
  p <- nutpie_sample(positive,num_draws=300,num_warmup=300,num_chains=4,cores=2,seed=432,progress="none",adaptation=adapt,init=list(x=c(1,2)),save_warmup=TRUE)
  expect_true(all(p[,,c("x[1]","x[2]")]>0))
  expect_equal(as.numeric(p[,,"square_x[1]"]),as.numeric(p[,,"x[1]"])^2,tolerance=1e-10)
  expect_equal(as.numeric(p[,,"square_x[2]"]),as.numeric(p[,,"x[2]"])^2,tolerance=1e-10)
  expect_gt(sd(as.numeric(p[,,"predictive"])),0.5)
  expected_mean <- 1+2*dnorm(-0.5)/(1-pnorm(-0.5))
  expect_lt(abs(mean(p[,,"x[1]"])-expected_mean),0.35)
}
init_forms <- list(NULL,0,list(x=c(0,0.5)),list(list(x=c(0,0.5)),list(x=c(2,3))),function(chain_id) list(x=c(chain_id+1, chain_id+1.5)))
for (ini in init_forms) {
  cat("INIT FORM",paste(deparse(ini),collapse=" "),"\n")
  p <- nutpie_sample(normal,num_draws=20,num_warmup=50,num_chains=2,seed=99,progress="none",init=ini)
  expect_equal(dim(p)[1:2],c(20L,2L))
}
a <- nutpie_sample(normal,num_draws=20,num_warmup=50,num_chains=2,seed=99,progress="none")
b <- nutpie_sample(normal,num_draws=20,num_warmup=50,num_chains=2,seed=99,progress="none")
expect_equal(as.numeric(a),as.numeric(b))
expect_error(nutpie_sample(normal,data=list(n=2,mu=9,sigma=2),progress="none"),"data|bound|rebind|attach")
gc()
c <- nutpie_sample(normal,num_draws=20,num_warmup=50,num_chains=2,seed=99,progress="none",pars="x")
expect_equal(dim(c)[1:2],c(20L,2L))
unlink(root, recursive = TRUE)
cat("BROAD SAMPLING PASSED\n")
