# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nutpieR_wrappers", use_symbols = TRUE, package_name = "nutpieR")

#' @usage NULL
#' @useDynLib nutpieR, .registration = TRUE
NULL

#' Sample from a 10-d standard normal using nuts-rs.
#' Returns a matrix of draws (rows = draws*chains, cols = parameters).
#' @param num_draws Number of draws per chain after warmup.
#' @param num_chains Number of parallel chains.
#' @param seed Random seed.
#' @keywords internal
sample_normal <- function(num_draws, num_chains, seed) .Call(wrap__sample_normal, num_draws, num_chains, seed)

#' Compile a Stan model to a shared library using BridgeStan.
#' Downloads BridgeStan sources if needed (first call is slow).
#' @param stan_file Path to the .stan file.
#' @param stanc_args Character vector of extra arguments for stanc compiler.
#' @param compile_args Character vector of extra arguments for make.
#' @return Path to the compiled shared library.
#' @keywords internal
compile_stan_model <- function(stan_file, stanc_args, compile_args) .Call(wrap__compile_stan_model, stan_file, stanc_args, compile_args)

#' @param lib_path Path to the compiled Stan shared library.
#' @param data_json JSON string with model data (empty string for no data).
#' @param num_draws Number of draws per chain after warmup.
#' @param num_warmup Number of warmup (tuning) draws per chain.
#' @param num_chains Number of parallel chains.
#' @param seed Random seed.
#' @param max_treedepth Maximum tree depth for NUTS.
#' @param target_accept Target acceptance probability for step size adaptation.
#' @param refresh Print progress every `refresh` draws per chain (0 = no progress).
#' @param init_mean Optional numeric vector of initial values in unconstrained space (legacy, jittered).
#' @param init_positions Optional list of numeric vectors (one per chain, or length 1 = broadcast).
#' @param jitter If TRUE, apply ±0.5 uniform jitter per coordinate.
#' @param save_warmup Whether to return warmup draws.
#' @param num_cores Number of CPU cores to use for parallel sampling.
#' @param store_divergences Whether to store detailed divergence information.
#' @param store_mass_matrix Whether to store the mass matrix at each draw.
#' @param low_rank Whether to use low-rank modified mass matrix adaptation.
#' @param mass_matrix_gamma Regularisation parameter for low-rank mass matrix (default 1e-5).
#' @param eigval_cutoff Eigenvalue cutoff for low-rank mass matrix (default 2.0).
#' @return A named list with draws matrix, num_warmup, num_chains, diagnostics,
#'   and optionally warmup_draws and warmup_diagnostics.
#' @keywords internal
sample_stan <- function(lib_path, data_json, num_draws, num_warmup, num_chains, seed, max_treedepth, target_accept, refresh, init_mean, init_positions, jitter, save_warmup, num_cores, store_divergences, store_mass_matrix, low_rank, mass_matrix_gamma, eigval_cutoff) .Call(wrap__sample_stan, lib_path, data_json, num_draws, num_warmup, num_chains, seed, max_treedepth, target_accept, refresh, init_mean, init_positions, jitter, save_warmup, num_cores, store_divergences, store_mass_matrix, low_rank, mass_matrix_gamma, eigval_cutoff)

#' Open a BridgeStan model and return an `ExternalPtr<BSHandle>` that caches
#' parameter-name metadata. The handle may be used by any of the `bs_*`
#' accessor functions without re-opening the shared library.
#' @keywords internal
bs_open <- function(lib_path, data_json, seed) .Call(wrap__bs_open, lib_path, data_json, seed)

#' Block-level parameter names (no transformed parameters / generated
#' quantities), dot-indexed. Length equals `bs_ndim_block()`.
#' @keywords internal
bs_block_names <- function(handle) .Call(wrap__bs_block_names, handle)

#' Full constrained parameter names (block + transformed parameters +
#' generated quantities), dot-indexed.
#' @keywords internal
bs_full_names <- function(handle) .Call(wrap__bs_full_names, handle)

#' Unconstrained parameter names, dot-indexed. Length equals `bs_ndim_unc()`.
#' @keywords internal
bs_unc_names <- function(handle) .Call(wrap__bs_unc_names, handle)

#' Number of unconstrained parameters.
#' @keywords internal
bs_ndim_unc <- function(handle) .Call(wrap__bs_ndim_unc, handle)

#' Number of block-level constrained parameters (no TP, no GQ).
#' @keywords internal
bs_ndim_block <- function(handle) .Call(wrap__bs_ndim_block, handle)

#' Map a flat block-level constrained vector (length `bs_ndim_block()`,
#' BridgeStan column-major / last-index-major order) to the unconstrained
#' space. No JSON parsing.
#' @keywords internal
bs_param_unconstrain <- function(handle, theta) .Call(wrap__bs_param_unconstrain, handle, theta)

#' Map a constrained point (JSON, CmdStan format) to the unconstrained space,
#' using an already-opened handle. All parameters must be present in the JSON.
#' @keywords internal
bs_param_unconstrain_json <- function(handle, init_json) .Call(wrap__bs_param_unconstrain_json, handle, init_json)

#' Map an unconstrained position to the full constrained scale (including
#' transformed parameters and generated quantities) using an already-opened
#' handle.
#' @keywords internal
bs_param_constrain <- function(handle, theta_unc, seed) .Call(wrap__bs_param_constrain, handle, theta_unc, seed)

#' Return the constrained parameter names (with transformed parameters and
#' generated quantities included) for a compiled Stan model. Indices use the
#' BridgeStan dot convention (e.g. `"beta.1.2"`).
#' @keywords internal
get_param_names <- function(lib_path, data_json) .Call(wrap__get_param_names, lib_path, data_json)

#' Return the unconstrained parameter names for a compiled Stan model.
#' Indices use the BridgeStan dot convention (e.g. `"beta.1.2"`).
#' @keywords internal
get_param_unc_names <- function(lib_path, data_json) .Call(wrap__get_param_unc_names, lib_path, data_json)

#' Map a constrained point (JSON, CmdStan format) to the unconstrained space.
#' All parameters must be present in the JSON.
#' @keywords internal
param_unconstrain_json_rs <- function(lib_path, data_json, init_json) .Call(wrap__param_unconstrain_json_rs, lib_path, data_json, init_json)

#' Map an unconstrained position to the constrained scale (including
#' transformed parameters and generated quantities).
#' @keywords internal
param_constrain_rs <- function(lib_path, data_json, theta_unc, seed) .Call(wrap__param_constrain_rs, lib_path, data_json, theta_unc, seed)


# nolint end
