# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nutpieR_wrappers", use_symbols = TRUE, package_name = "nutpieR")

#' @usage NULL
#' @useDynLib nutpieR, .registration = TRUE
NULL

#' Sample from a 10-d standard normal using nuts-rs.
#' Returns a matrix of draws (rows = draws*chains, cols = parameters).
#' @param num_draws Number of draws per chain after warmup.
#' @param num_chains Number of parallel chains.
#' @param seed Random seed.
#' @export
sample_normal <- function(num_draws, num_chains, seed) .Call(wrap__sample_normal, num_draws, num_chains, seed)


# nolint end
