# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_nutpieR_wrappers", use_symbols = TRUE, package_name = "nutpieR")

#' @usage NULL
#' @useDynLib nutpieR, .registration = TRUE
NULL

#' Sample from a 10-d standard normal using nuts-rs.
#' Returns a matrix of draws (rows = draws*chains, cols = parameters).
#' @param num_draws Number of draws per chain after warmup.
#' @param num_chains Number of parallel chains.
#' @param seed Random seed.
#' @keywords internal
sample_normal <- function(num_draws, num_chains, seed) .Call(wrap__sample_normal, num_draws, num_chains, seed)

#' Compile a Stan model to a shared library using BridgeStan.
#' Downloads BridgeStan sources if needed (first call is slow).
#' @param stan_file Path to the .stan file.
#' @param stanc_args Character vector of extra arguments for stanc compiler.
#' @param compile_args Character vector of extra arguments for make.
#' @return Path to the compiled shared library.
#' @keywords internal
compile_stan_model <- function(stan_file, stanc_args, compile_args) .Call(wrap__compile_stan_model, stan_file, stanc_args, compile_args)

#' Sample from a Stan model using nuts-rs NUTS sampler.
#' @param lib_path Path to the compiled Stan shared library.
#' @param data_json JSON string with model data (empty string for no data).
#' @param num_draws Number of draws per chain after warmup.
#' @param num_warmup Number of warmup (tuning) draws per chain.
#' @param num_chains Number of parallel chains.
#' @param seed Random seed.
#' @param max_treedepth Maximum tree depth for NUTS.
#' @param target_accept Target acceptance probability for step size adaptation.
#' @param refresh Print progress every `refresh` draws per chain (0 = no progress).
#' @param init_mean Optional numeric vector of initial values in unconstrained space.
#' @param save_warmup Whether to return warmup draws.
#' @param num_cores Number of CPU cores to use for parallel sampling.
#' @param store_divergences Whether to store detailed divergence information.
#' @param store_mass_matrix Whether to store the mass matrix at each draw.
#' @param low_rank Whether to use low-rank modified mass matrix adaptation.
#' @param mass_matrix_gamma Regularisation parameter for low-rank mass matrix.
#' @param eigval_cutoff Eigenvalue cutoff for low-rank mass matrix.
#' @return A named list with draws matrix, num_warmup, num_chains, diagnostics,
#'   and optionally warmup_draws and warmup_diagnostics.
#' @keywords internal
sample_stan <- function(lib_path, data_json, num_draws, num_warmup, num_chains, seed, max_treedepth, target_accept, refresh, init_mean, save_warmup, num_cores, store_divergences, store_mass_matrix, low_rank, mass_matrix_gamma, eigval_cutoff) .Call(wrap__sample_stan, lib_path, data_json, num_draws, num_warmup, num_chains, seed, max_treedepth, target_accept, refresh, init_mean, save_warmup, num_cores, store_divergences, store_mass_matrix, low_rank, mass_matrix_gamma, eigval_cutoff)


# nolint end
